// Code generated by "mock-api-gen -type Consul -pkg mockconsul -endpoints status.json -output ./status.go"; DO NOT EDIT.

package mockconsul

import (
	mockapi "github.com/mkeeler/mock-http-api"
)

func (m *Consul) StatusLeader(status int, reply string) *mockapi.MockAPICall {
	req := mockapi.NewMockRequest("GET", "/v1/status/leader")

	return m.WithJSONReply(req, status, reply)
}

func (m *Consul) StatusPeers(status int, reply []string) *mockapi.MockAPICall {
	req := mockapi.NewMockRequest("GET", "/v1/status/peers")

	return m.WithJSONReply(req, status, reply)
}
